[project]
name = "Spec Manager v1.3.18"
version = "0.0.0"
authors = []
license = "UNLICENSED"
target = "xlsm"

[src]
AccessControl = "src/AccessControl.bas"
Account = "src/Account.cls"
ActionLog = "src/ActionLog.cls"
App = "src/App.cls"
Arrays = "src/Arrays.bas"
Convert = "src/Convert.bas"
DataAccess = "src/DataAccess.bas"
DataFrame = "src/DataFrame.cls"
DocumentPrinter = "src/DocumentPrinter.cls"
Enums = "src/Enums.bas"
Factory = "src/Factory.bas"
GuiCommands = "src/GuiCommands.bas"
IDatabase = "src/IDatabase.cls"
IQueryable = "src/IQueryable.cls"
JsonVBA = "src/JsonVBA.bas"
KrishDll = "src/KrishDll.cls"
Logger = "src/Logger.cls"
PromptHandler = "src/PromptHandler.bas"
RbaParser = "src/RbaParser.bas"
RevisionLogger = "src/RevisionLogger.cls"
SQLiteDatabase = "src/SQLiteDatabase.cls"
SpecManager = "src/SpecManager.bas"
Specification = "src/Specification.cls"
SpecificationTemplate = "src/SpecificationTemplate.cls"
SqlTransaction = "src/SqlTransaction.cls"
Symbols = "src/Symbols.bas"
System = "src/System.bas"
TDialog = "src/TDialog.cls"
Table = "src/Table.cls"
Tests = "src/Tests.bas"
ThisWorkbook = "src/ThisWorkbook.cls"
Types = "src/Types.bas"
UserAction = "src/UserAction.cls"
Utils = "src/Utils.bas"
formConsole = "src/formConsole.frm"
formCreateGeneric = "src/formCreateGeneric.frm"
formCreateSpec = "src/formCreateSpec.frm"
formEditTemplate = "src/formEditTemplate.frm"
formMainMenu = "src/formMainMenu.frm"
formNewSpecInput = "src/formNewSpecInput.frm"
formNewTemplateInput = "src/formNewTemplateInput.frm"
formPrintSpecifications = "src/formPrintSpecifications.frm"
formSpecConfig = "src/formSpecConfig.frm"
formUserPrompt = "src/formUserPrompt.frm"
formViewSpecs = "src/formViewSpecs.frm"
formWarpDataSheet = "src/formWarpDataSheet.frm"
modProgress = "src/modProgress.bas"
ufProgress = "src/ufProgress.frm"

[references]

[references.Scripting]
version = "1.0"
guid = "{420B2830-E718-11CF-893D-00A0C9054228}"
