'============================================================================
'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
'NOTES: This is the DEVELOPER VERSION of the Spec Manager Application.
' Excel macro to export all VBA source code in this
' project to text files for proper source control versioning
' Requires enabling the Excel setting in Options/Trust Center/Trust
' Center Settings/Macro Settings/Trust access to the VBA project object model
'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
'=============================================================================
Private retry As Long

