VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IQueryable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' Interface to extract sql information
' Public Property Let SubIdentifiers(value As Variant)
' End Property
' Public Property Get SubIdentifiers() As String
' End Property
' Public Property Let Identifier(value As Variant)
' End Property
' Public Property Get Identifier() As String
' End Property


Function GetValueLabels() As String
End Function

Function GetValues() As String
End Function



