VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISearchForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'====================================
'CLASS DESCRIPTION:
' Description
'====================================
'Factory Module Constructor function:
'Function CreateISearchForm() As ISearchForm
'----------
' METHODS
'----------
Public Function Search(id_value As String)
End Function
Public Function DisplayResults()
End Function
