Attribute VB_Name = "Symbols"
Option Explicit
' String Constants
Public Const PUBLIC_DIR               As String = "S:\Data Manager"
Public Const SM_PATH                  As String = "C:\Users\"
Public Const DATABASE_PATH            As String = "C:\Users\cruff\Documents\Projects\source\Spec-Manager\Database\SAATI_Spec_Manager.db3"
'Public Const DATABASE_PATH            As String = "S:\Data Manager\Database\SAATI_Spec_Manager.db3"
Public Const TEST_DATABASE_PATH       As String = ""
Public Const nullstr                  As String = vbNullString

' SPEC MANAGER ERROR DESCRIPTIONS:
Public Const SM_SEARCH_SUCCESS     As Long = 440
Public Const SM_SEARCH_FAILURE     As Long = 441
Public Const SM_SEARCH_AGAIN       As Long = 443
Public Const SM_REGEX_ERROR        As Long = 444
Public Const SM_MATERIAL_EXISTS    As Long = 445
Public Const SM_INTERNAL_ERROR     As Long = 446

' DATABASE ERROR DESCRIPTIONS:
Public Const DB_PUSH_SUCCESS            As Long = 900
Public Const DB_PUSH_FAILURE            As Long = 901
Public Const DB_DELETE_SUCCESS          As Long = 902
Public Const DB_DELETE_FAILURE          As Long = 903
Public Const DB_SELECT_SUCCESS          As Long = 904
Public Const DB_SELECT_FAILURE          As Long = 905
Public Const DB_PUSH_DENIED             As Long = 906
Public Const DB_DELETE_DENIED           As Long = 907
Public Const DB_TRANSACTION_FAILURE     As Long = 908
Public Const DB_TRANSACTION_SUCCESS     As Long = 909

' ACCOUNT PRIVLEDGE LEVELS
Public Const USER_MANAGER          As Long = 21
Public Const USER_READONLY         As Long = 20
Public Const USER_ADMIN            As Long = 25

' Returned from SQLite3Initialize
Public Const SQLITE_INIT_OK     As Long = 0
Public Const SQLITE_INIT_ERROR  As Long = 1

' SQLite data types
Public Const SQLITE_INTEGER  As Long = 1
Public Const SQLITE_FLOAT    As Long = 2
Public Const SQLITE_TEXT     As Long = 3
Public Const SQLITE_BLOB     As Long = 4
Public Const SQLITE_NULL     As Long = 5

' SQLite atandard return
Public Const SQLITE_OK         As Long = 0   ' Successful result
Public Const SQLITE_ERROR      As Long = 1   ' SQL error or missing database
Public Const SQLITE_INTERNAL   As Long = 2   ' Internal logic error in SQLite
Public Const SQLITE_PERM       As Long = 3   ' Access permission denied
Public Const SQLITE_ABORT      As Long = 4   ' Callback routine requested an abort
Public Const SQLITE_BUSY       As Long = 5   ' The database file is locked
Public Const SQLITE_LOCKED     As Long = 6   ' A table in the database is locked
Public Const SQLITE_NOMEM      As Long = 7   ' A malloc() failed
Public Const SQLITE_READONLY   As Long = 8   ' Attempt to write a readonly database
Public Const SQLITE_INTERRUPT  As Long = 9   ' Operation terminated by sqlite3_interrupt()
Public Const SQLITE_IOERR      As Long = 10  ' Some kind of disk I/O error occurred
Public Const SQLITE_CORRUPT    As Long = 11  ' The database disk image is malformed
Public Const SQLITE_NOTFOUND   As Long = 12  ' NOT USED. Table or record not found
Public Const SQLITE_FULL       As Long = 13  ' Insertion failed because database is full
Public Const SQLITE_CANTOPEN   As Long = 14  ' Unable to open the database file
Public Const SQLITE_PROTOCOL   As Long = 15  ' NOT USED. Database lock protocol error
Public Const SQLITE_EMPTY      As Long = 16  ' Database is empty
Public Const SQLITE_SCHEMA     As Long = 17  ' The database schema changed
Public Const SQLITE_TOOBIG     As Long = 18  ' String or BLOB exceeds size limit
Public Const SQLITE_CONSTRAINT As Long = 19  ' Abort due to constraint violation
Public Const SQLITE_MISMATCH   As Long = 20  ' Data type mismatch
Public Const SQLITE_MISUSE     As Long = 21  ' Library used incorrectly
Public Const SQLITE_NOLFS      As Long = 22  ' Uses OS features not supported on host
Public Const SQLITE_AUTH       As Long = 23  ' Authorization denied
Public Const SQLITE_FORMAT     As Long = 24  ' Auxiliary database format error
Public Const SQLITE_RANGE      As Long = 25  ' 2nd parameter to sqlite3_bind out of range
Public Const SQLITE_NOTADB     As Long = 26  ' File opened that is not a database file
Public Const SQLITE_ROW        As Long = 100 ' sqlite3_step() has another row ready
Public Const SQLITE_DONE       As Long = 101 ' sqlite3_step() has finished executing

' Extended error codes
Public Const SQLITE_IOERR_READ               As Long = 266  '(SQLITE_IOERR | (1<<8))
Public Const SQLITE_IOERR_SHORT_READ         As Long = 522  '(SQLITE_IOERR | (2<<8))
Public Const SQLITE_IOERR_WRITE              As Long = 778  '(SQLITE_IOERR | (3<<8))
Public Const SQLITE_IOERR_FSYNC              As Long = 1034 '(SQLITE_IOERR | (4<<8))
Public Const SQLITE_IOERR_DIR_FSYNC          As Long = 1290 '(SQLITE_IOERR | (5<<8))
Public Const SQLITE_IOERR_TRUNCATE           As Long = 1546 '(SQLITE_IOERR | (6<<8))
Public Const SQLITE_IOERR_FSTAT              As Long = 1802 '(SQLITE_IOERR | (7<<8))
Public Const SQLITE_IOERR_UNLOCK             As Long = 2058 '(SQLITE_IOERR | (8<<8))
Public Const SQLITE_IOERR_RDLOCK             As Long = 2314 '(SQLITE_IOERR | (9<<8))
Public Const SQLITE_IOERR_DELETE             As Long = 2570 '(SQLITE_IOERR | (10<<8))
Public Const SQLITE_IOERR_BLOCKED            As Long = 2826 '(SQLITE_IOERR | (11<<8))
Public Const SQLITE_IOERR_NOMEM              As Long = 3082 '(SQLITE_IOERR | (12<<8))
Public Const SQLITE_IOERR_ACCESS             As Long = 3338 '(SQLITE_IOERR | (13<<8))
Public Const SQLITE_IOERR_CHECKRESERVEDLOCK  As Long = 3594 '(SQLITE_IOERR | (14<<8))
Public Const SQLITE_IOERR_LOCK               As Long = 3850 '(SQLITE_IOERR | (15<<8))
Public Const SQLITE_IOERR_CLOSE              As Long = 4106 '(SQLITE_IOERR | (16<<8))
Public Const SQLITE_IOERR_DIR_CLOSE          As Long = 4362 '(SQLITE_IOERR | (17<<8))
Public Const SQLITE_LOCKED_SHAREDCACHE       As Long = 265  '(SQLITE_LOCKED | (1<<8) )

' Flags For File Open Operations
Public Const SQLITE_OPEN_READONLY           As Long = 1       ' Ok for sqlite3_open_v2()
Public Const SQLITE_OPEN_READWRITE          As Long = 2       ' Ok for sqlite3_open_v2()
Public Const SQLITE_OPEN_CREATE             As Long = 4       ' Ok for sqlite3_open_v2()
Public Const SQLITE_OPEN_DELETEONCLOSE      As Long = 8       ' VFS only
Public Const SQLITE_OPEN_EXCLUSIVE          As Long = 16      ' VFS only
Public Const SQLITE_OPEN_AUTOPROXY          As Long = 32      ' VFS only
Public Const SQLITE_OPEN_URI                As Long = 64      ' Ok for sqlite3_open_v2()
Public Const SQLITE_OPEN_MEMORY             As Long = 128     ' Ok for sqlite3_open_v2()
Public Const SQLITE_OPEN_MAIN_DB            As Long = 256     ' VFS only
Public Const SQLITE_OPEN_TEMP_DB            As Long = 512     ' VFS only
Public Const SQLITE_OPEN_TRANSIENT_DB       As Long = 1024    ' VFS only
Public Const SQLITE_OPEN_MAIN_JOURNAL       As Long = 2048    ' VFS only
Public Const SQLITE_OPEN_TEMP_JOURNAL       As Long = 4096    ' VFS only
Public Const SQLITE_OPEN_SUBJOURNAL         As Long = 8192    ' VFS only
Public Const SQLITE_OPEN_MASTER_JOURNAL     As Long = 16384   ' VFS only
Public Const SQLITE_OPEN_NOMUTEX            As Long = 32768   ' Ok for sqlite3_open_v2()
Public Const SQLITE_OPEN_FULLMUTEX          As Long = 65536   ' Ok for sqlite3_open_v2()
Public Const SQLITE_OPEN_SHAREDCACHE        As Long = 131072  ' Ok for sqlite3_open_v2()
Public Const SQLITE_OPEN_PRIVATECACHE       As Long = 262144  ' Ok for sqlite3_open_v2()
Public Const SQLITE_OPEN_WAL                As Long = 524288  ' VFS only

' VBA-TOOLS COLOR CODES
Public Const SAATI_BLUE             As String = "#153fd6"
Public Const default_color          As String = "#2BBBAD"
Public Const default_color_dark     As String = "#00695c"
Public Const primary_color          As String = "#4285F4"
Public Const primary_color_dark     As String = "#0d47a1"
Public Const secondary_color        As String = "#aa66cc"
Public Const secondary_color_dark   As String = "#9933CC"
Public Const DANGER_COLOR           As String = "#FF4444"
Public Const DANGER_COLOR_DARK      As String = "#CC0000"
Public Const WARNING_COLOR          As String = "#FFBB33"
Public Const WARNING_COLOR_DARK     As String = "#FF8800"
Public Const SUCCESS_COLOR          As String = "#00C851"
Public Const SUCCESS_COLOR_DARK     As String = "#007E33"
Public Const INFO_COLOR             As String = "#33B5E5"
Public Const INFO_COLOR_DARK        As String = "#0099CC"
Public Const PURPLE_LIGHTEN_1       As String = "#ab47bc"
Public Const AMBER                  As String = "#ffc107"
Public Const AMBER_ACCENT_1         As String = "#ffe57f"
Public Const AMBER_ACCENT_2         As String = "#ffd740"
Public Const AMBER_ACCENT_3         As String = "#ffc400"
Public Const AMBER_ACCENT_4         As String = "#ffab00"
Public Const AMBER_DARKEN_1         As String = "#ffb300"
Public Const AMBER_DARKEN_2         As String = "#ffa000"
Public Const AMBER_DARKEN_3         As String = "#ff8f00"
Public Const AMBER_DARKEN_4         As String = "#ff6f00"
Public Const AMBER_LIGHTEN_1        As String = "#ffca28"
Public Const AMBER_LIGHTEN_2        As String = "#ffd54f"
Public Const AMBER_LIGHTEN_3        As String = "#ffe082"
Public Const AMBER_LIGHTEN_4        As String = "#ffecb3"
Public Const AMBER_LIGHTEN_5        As String = "#fff8e1"
Public Const BLACK                  As String = "#000000"
Public Const BLUE                   As String = "#2196f3"
Public Const BLUE_ACCENT_1          As String = "#82b1ff"
Public Const BLUE_ACCENT_2          As String = "#448aff"
Public Const BLUE_ACCENT_3          As String = "#2979ff"
Public Const BLUE_ACCENT_4          As String = "#2962ff"
Public Const BLUE_DARKEN_1          As String = "#1e88e5"
Public Const BLUE_DARKEN_2          As String = "#1976d2"
Public Const BLUE_DARKEN_3          As String = "#1565c0"
Public Const BLUE_DARKEN_4          As String = "#0d47a1"
Public Const BLUE_GREY              As String = "#607d8b"
Public Const BLUE_GREY_DARKEN_1     As String = "#546e7a"
Public Const BLUE_GREY_DARKEN_2     As String = "#455a64"
Public Const BLUE_GREY_DARKEN_3     As String = "#37474f"
Public Const BLUE_GREY_DARKEN_4     As String = "#263238"
Public Const BLUE_GREY_LIGHTEN_1    As String = "#78909c"
Public Const BLUE_GREY_LIGHTEN_2    As String = "#90a4ae"
Public Const BLUE_GREY_LIGHTEN_3    As String = "#b0bec5"
Public Const BLUE_GREY_LIGHTEN_4    As String = "#cfd8dc"
Public Const BLUE_GREY_LIGHTEN_5    As String = "#eceff1"
Public Const BLUE_LIGHTEN_1         As String = "#42a5f5"
Public Const BLUE_LIGHTEN_2         As String = "#64b5f6"
Public Const BLUE_LIGHTEN_3         As String = "#90caf9"
Public Const BLUE_LIGHTEN_4         As String = "#bbdefb"
Public Const BLUE_LIGHTEN_5         As String = "#e3f2fd"
Public Const BROWN                  As String = "#795548"
Public Const BROWN_DARKEN_1         As String = "#6d4c41"
Public Const BROWN_DARKEN_2         As String = "#5d4037"
Public Const BROWN_DARKEN_3         As String = "#4e342e"
Public Const BROWN_DARKEN_4         As String = "#3e2723"
Public Const BROWN_LIGHTEN_1        As String = "#8d6e63"
Public Const BROWN_LIGHTEN_2        As String = "#a1887f"
Public Const BROWN_LIGHTEN_3        As String = "#bcaaa4"
Public Const BROWN_LIGHTEN_4        As String = "#d7ccc8"
Public Const BROWN_LIGHTEN_5        As String = "#efebe9"
Public Const CYAN                   As String = "#00bcd4"
Public Const CYAN_ACCENT_1          As String = "#84ffff"
Public Const CYAN_ACCENT_2          As String = "#18ffff"
Public Const CYAN_ACCENT_3          As String = "#00e5ff"
Public Const CYAN_ACCENT_4          As String = "#00b8d4"
Public Const CYAN_DARKEN_1          As String = "#00acc1"
Public Const CYAN_DARKEN_2          As String = "#0097a7"
Public Const CYAN_DARKEN_3          As String = "#00838f"
Public Const CYAN_DARKEN_4          As String = "#006064"
Public Const CYAN_LIGHTEN_1         As String = "#26c6da"
Public Const CYAN_LIGHTEN_2         As String = "#4dd0e1"
Public Const CYAN_LIGHTEN_3         As String = "#80deea"
Public Const CYAN_LIGHTEN_4         As String = "#b2ebf2"
Public Const CYAN_LIGHTEN_5         As String = "#e0f7fa"
Public Const DEEP_ORANGE            As String = "#ff5722"
Public Const DEEP_ORANGE_DARKEN_1   As String = "#f4511e"
Public Const DEEP_ORANGE_DARKEN_2   As String = "#e64a19"
Public Const DEEP_ORANGE_DARKEN_3   As String = "#d84315"
Public Const DEEP_ORANGE_DARKEN_4   As String = "#bf360c"
Public Const DEEP_ORANGE_LIGHTEN_1  As String = "#ff7043"
Public Const DEEP_ORANGE_LIGHTEN_2  As String = "#ff8a65"
Public Const DEEP_ORANGE_LIGHTEN_3  As String = "#ffab91"
Public Const DEEP_ORANGE_LIGHTEN_4  As String = "#ffccbc"
Public Const DEEP_ORANGE_LIGHTEN_5  As String = "#fbe9e7"
Public Const DEEP_PURPLE            As String = "#673ab7"
Public Const DEEP_PURPLE_ACCENT_1   As String = "#b388ff"
Public Const DEEP_PURPLE_ACCENT_2   As String = "#7c4dff"
Public Const DEEP_PURPLE_ACCENT_3   As String = "#651fff"
Public Const DEEP_PURPLE_ACCENT_4   As String = "#6200ea"
Public Const DEEP_PURPLE_DARKEN_1   As String = "#5e35b1"
Public Const DEEP_PURPLE_DARKEN_2   As String = "#512da8"
Public Const DEEP_PURPLE_DARKEN_3   As String = "#4527a0"
Public Const DEEP_PURPLE_DARKEN_4   As String = "#311b92"
Public Const DEEP_PURPLE_LIGHTEN_1  As String = "#7e57c2"
Public Const DEEP_PURPLE_LIGHTEN_2  As String = "#9575cd"
Public Const DEEP_PURPLE_LIGHTEN_3  As String = "#b39ddb"
Public Const DEEP_PURPLE_LIGHTEN_4  As String = "#d1c4e9"
Public Const DEEP_PURPLE_LIGHTEN_5  As String = "#ede7f6"
Public Const GREEN                  As String = "#4caf50"
Public Const GREEN_ACCENT_1         As String = "#b9f6ca"
Public Const GREEN_ACCENT_2         As String = "#69f0ae"
Public Const GREEN_ACCENT_3         As String = "#00e676"
Public Const GREEN_ACCENT_4         As String = "#00c853"
Public Const GREEN_DARKEN_1         As String = "#43a047"
Public Const GREEN_DARKEN_2         As String = "#388e3c"
Public Const GREEN_DARKEN_3         As String = "#2e7d32"
Public Const GREEN_DARKEN_4         As String = "#1b5e20"
Public Const GREEN_LIGHTEN_1        As String = "#66bb6a"
Public Const GREEN_LIGHTEN_2        As String = "#81c784"
Public Const GREEN_LIGHTEN_3        As String = "#a5d6a7"
Public Const GREEN_LIGHTEN_4        As String = "#c8e6c9"
Public Const GREEN_LIGHTEN_5        As String = "#e8f5e9"
Public Const GREY                   As String = "#9e9e9e"
Public Const GREY_DARKEN_1          As String = "#757575"
Public Const GREY_DARKEN_2          As String = "#616161"
Public Const GREY_DARKEN_3          As String = "#424242"
Public Const GREY_DARKEN_4          As String = "#212121"
Public Const GREY_LIGHTEN_1         As String = "#bdbdbd"
Public Const GREY_LIGHTEN_2         As String = "#e0e0e0"
Public Const GREY_LIGHTEN_3         As String = "#eeeeee"
Public Const GREY_LIGHTEN_4         As String = "#f5f5f5"
Public Const GREY_LIGHTEN_5         As String = "#fafafa"
Public Const INDIGO                 As String = "#3f51b5"
Public Const INDIGO_ACCENT_1        As String = "#8c9eff"
Public Const INDIGO_ACCENT_2        As String = "#536dfe"
Public Const INDIGO_ACCENT_3        As String = "#3d5afe"
Public Const INDIGO_ACCENT_4        As String = "#304ffe"
Public Const INDIGO_DARKEN_1        As String = "#3949ab"
Public Const INDIGO_DARKEN_2        As String = "#303f9f"
Public Const INDIGO_DARKEN_3        As String = "#283593"
Public Const INDIGO_DARKEN_4        As String = "#1a237e"
Public Const INDIGO_LIGHTEN_1       As String = "#5c6bc0"
Public Const INDIGO_LIGHTEN_2       As String = "#7986cb"
Public Const INDIGO_LIGHTEN_3       As String = "#9fa8da"
Public Const INDIGO_LIGHTEN_4       As String = "#c5cae9"
Public Const INDIGO_LIGHTEN_5       As String = "#e8eaf6"
Public Const LIGHT_BLUE             As String = "#03a9f4"
Public Const LIGHT_BLUE_ACCENT_1    As String = "#l80d8ff"
Public Const LIGHT_BLUE_ACCENT_2    As String = "#40c4ff"
Public Const LIGHT_BLUE_ACCENT_3    As String = "#00b0ff"
Public Const LIGHT_BLUE_ACCENT_4    As String = "#0091ea"
Public Const LIGHT_BLUE_DARKEN_1    As String = "#039be5"
Public Const LIGHT_BLUE_DARKEN_2    As String = "#0288d1"
Public Const LIGHT_BLUE_DARKEN_3    As String = "#0277bd"
Public Const LIGHT_BLUE_DARKEN_4    As String = "#01579b"
Public Const LIGHT_BLUE_LIGHTEN_1   As String = "#29b6f6"
Public Const LIGHT_BLUE_LIGHTEN_2   As String = "#4fc3f7"
Public Const LIGHT_BLUE_LIGHTEN_3   As String = "#81d4fa"
Public Const LIGHT_BLUE_LIGHTEN_4   As String = "#b3e5fc"
Public Const LIGHT_BLUE_LIGHTEN_5   As String = "#e1f5fe"
Public Const LIGHT_GREEN            As String = "#8bc34a"
Public Const LIGHT_GREEN_ACCENT_1   As String = "#ccff90"
Public Const LIGHT_GREEN_ACCENT_2   As String = "#b2ff59"
Public Const LIGHT_GREEN_ACCENT_3   As String = "#76ff03"
Public Const LIGHT_GREEN_ACCENT_4   As String = "#64dd17"
Public Const LIGHT_GREEN_DARKEN_1   As String = "#7cb342"
Public Const LIGHT_GREEN_DARKEN_2   As String = "#689f38"
Public Const LIGHT_GREEN_DARKEN_3   As String = "#558b2f"
Public Const LIGHT_GREEN_DARKEN_4   As String = "#33691e"
Public Const LIGHT_GREEN_LIGHTEN_1  As String = "#9ccc65"
Public Const LIGHT_GREEN_LIGHTEN_2  As String = "#aed581"
Public Const LIGHT_GREEN_LIGHTEN_3  As String = "#c5e1a5"
Public Const LIGHT_GREEN_LIGHTEN_4  As String = "#dcedc8"
Public Const LIGHT_GREEN_LIGHTEN_5  As String = "#f1f8e9"
Public Const LIME                   As String = "#cddc39"
Public Const LIME_ACCENT_1          As String = "#f4ff81"
Public Const LIME_ACCENT_2          As String = "#eeff41"
Public Const LIME_ACCENT_3          As String = "#c6ff00"
Public Const LIME_ACCENT_4          As String = "#aeea00"
Public Const LIME_DARKEN_1          As String = "#c0ca33"
Public Const LIME_DARKEN_2          As String = "#afb42b"
Public Const LIME_DARKEN_3          As String = "#9e9d24"
Public Const LIME_DARKEN_4          As String = "#827717"
Public Const LIME_LIGHTEN_1         As String = "#d4e157"
Public Const LIME_LIGHTEN_2         As String = "#dce775"
Public Const LIME_LIGHTEN_3         As String = "#e6ee9c"
Public Const LIME_LIGHTEN_4         As String = "#f0f4c3"
Public Const LIME_LIGHTEN_5         As String = "#f9fbe7"
Public Const MDB_COLOR              As String = "#45526e"
Public Const MDB_COLOR_DARKEN_1     As String = "#3b465e"
Public Const MDB_COLOR_DARKEN_2     As String = "#2e3951"
Public Const MDB_COLOR_DARKEN_3     As String = "#1c2a48"
Public Const MDB_COLOR_DARKEN_4     As String = "#1c2331"
Public Const MDB_COLOR_LIGHTEN_1    As String = "#59698d"
Public Const MDB_COLOR_LIGHTEN_2    As String = "#7283a7"
Public Const MDB_COLOR_LIGHTEN_3    As String = "#929fba"
Public Const MDB_COLOR_LIGHTEN_4    As String = "#b1bace"
Public Const MDB_COLOR_LIGHTEN_5    As String = "#d0d6e2"
Public Const ORANGE                 As String = "#ff9800"
Public Const ORANGE_ACCENT_1        As String = "#ffd180"
Public Const ORANGE_ACCENT_2        As String = "#ffab40"
Public Const ORANGE_ACCENT_3        As String = "#ff9100"
Public Const ORANGE_ACCENT_4        As String = "#ff6d00"
Public Const ORANGE_DARKEN_1        As String = "#fb8c00"
Public Const ORANGE_DARKEN_2        As String = "#f57c00"
Public Const ORANGE_DARKEN_3        As String = "#ef6c00"
Public Const ORANGE_DARKEN_4        As String = "#e65100"
Public Const ORANGE_LIGHTEN_1       As String = "#ffa726"
Public Const ORANGE_LIGHTEN_2       As String = "#ffb74d"
Public Const ORANGE_LIGHTEN_3       As String = "#ffcc80"
Public Const ORANGE_LIGHTEN_4       As String = "#ffe0b2"
Public Const ORANGE_LIGHTEN_5       As String = "#fff3e0"
Public Const PINK                   As String = "#e91e63"
Public Const PINK_ACCENT_1          As String = "#ff80ab"
Public Const PINK_ACCENT_2          As String = "#ff4081"
Public Const PINK_ACCENT_3          As String = "#f50057"
Public Const PINK_ACCENT_4          As String = "#c51162"
Public Const PINK_DARKEN_1          As String = "#d81b60"
Public Const PINK_DARKEN_2          As String = "#c2185b"
Public Const PINK_DARKEN_3          As String = "#ad1457"
Public Const PINK_DARKEN_4          As String = "#880e4f"
Public Const PINK_LIGHTEN_1         As String = "#ec407a"
Public Const PINK_LIGHTEN_2         As String = "#f06292"
Public Const PINK_LIGHTEN_3         As String = "#f48fb1"
Public Const PINK_LIGHTEN_4         As String = "#f8bbd0"
Public Const PINK_LIGHTEN_5         As String = "#fce4ec"
Public Const PURPLE                 As String = "#9c27b0"
Public Const PURPLE_ACCENT_4        As String = "#aa00ff"
Public Const PURPLE_ACCENT_1        As String = "#d500f9"
Public Const PURPLE_ACCENT_2        As String = "#e040fb"
Public Const PURPLE_ACCENT_3        As String = "#ea80fc"
Public Const PURPLE_DARKEN_1        As String = "#8e24aa"
Public Const PURPLE_DARKEN_2        As String = "#7b1fa2"
Public Const PURPLE_DARKEN_3        As String = "#6a1b9a"
Public Const PURPLE_DARKEN_4        As String = "#4a148c"
Public Const PURPLE_LIGHTEN_2       As String = "#ba68c8"
Public Const PURPLE_LIGHTEN_3       As String = "#ce93d8"
Public Const PURPLE_LIGHTEN_4       As String = "#e1bee7"
Public Const PURPLE_LIGHTEN_5       As String = "#f3e5f5"
Public Const RED                    As String = "#f44336"
Public Const RED_ACCENT_1           As String = "#ff8a80"
Public Const RED_ACCENT_2           As String = "#ff5252"
Public Const RED_ACCENT_3           As String = "#ff1744"
Public Const RED_ACCENT_4           As String = "#d50000"
Public Const RED_DARKEN_1           As String = "#e53935"
Public Const RED_DARKEN_2           As String = "#d32f2f"
Public Const RED_DARKEN_3           As String = "#c62828"
Public Const RED_DARKEN_4           As String = "#b71c1c"
Public Const RED_LIGHTEN_1          As String = "#ef5350"
Public Const RED_LIGHTEN_2          As String = "#e57373"
Public Const RED_LIGHTEN_3          As String = "#ef9a9a"
Public Const RED_LIGHTEN_4          As String = "#ffcdd2"
Public Const RED_LIGHTEN_5          As String = "#ffebee"
Public Const TEAL                   As String = "#009688"
Public Const TEAL_ACCENT_1          As String = "#a7ffeb"
Public Const TEAL_ACCENT_2          As String = "#64ffda"
Public Const TEAL_ACCENT_3          As String = "#1de9b6"
Public Const TEAL_ACCENT_4          As String = "#00bfa5"
Public Const TEAL_DARKEN_1          As String = "#00897b"
Public Const TEAL_DARKEN_2          As String = "#00796b"
Public Const TEAL_DARKEN_3          As String = "#00695c"
Public Const TEAL_DARKEN_4          As String = "#004d40"
Public Const TEAL_LIGHTEN_1         As String = "#26a69a"
Public Const TEAL_LIGHTEN_2         As String = "#4db6ac"
Public Const TEAL_LIGHTEN_3         As String = "#80cbc4"
Public Const TEAL_LIGHTEN_4         As String = "#b2dfdb"
Public Const TEAL_LIGHTEN_5         As String = "#e0f2f1"
Public Const WHITE                  As String = "#ffffff"
Public Const YELLOW                 As String = "#ffeb3b"
Public Const YELLOW_ACCENT_1        As String = "#ffff8d"
Public Const YELLOW_ACCENT_2        As String = "#ffff00"
Public Const YELLOW_ACCENT_3        As String = "#ffea00"
Public Const YELLOW_ACCENT_4        As String = "#ffd600"
Public Const YELLOW_DARKEN_1        As String = "#fdd835"
Public Const YELLOW_DARKEN_2        As String = "#fbc02d"
Public Const YELLOW_DARKEN_3        As String = "#f9a825"
Public Const YELLOW_DARKEN_4        As String = "#f57f17"
Public Const YELLOW_LIGHTEN_1       As String = "#ffee58"
Public Const YELLOW_LIGHTEN_2       As String = "#fff176"
Public Const YELLOW_LIGHTEN_3       As String = "#fff59d"
Public Const YELLOW_LIGHTEN_4       As String = "#fff9c4"
Public Const YELLOW_LIGHTEN_5       As String = "#fffde7"
